[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.inviariant]
fail_on_revert = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
